### ISSUE TITLE
Build time?

### ISSUE THREAD

**Issue by EricWarnke** [DougBeney/jekyll-pug#11] opened 2017-11-10 19:53 UTC
I was using jekyll-pug for a few isolated pages. When I finally changed a global include, my nav, it took my build time from 7s to 76s. Any idea how to troubleshoot or improve this?

**Comment by DougBeney** [comment] 2017-11-10 21:05
Hi, Eric!

- Was it a single include tag that caused the 7s to 76s?
- How large is your project?
- Any steps I could do to reproduce this? (Or if your project is a public repo, feel free to share the link)

One thing I recently noticed is that pug includes are faster than Jekyll/Liquid include tags. 

So any tags that are like:

`{% include nav %}`

...would perform better as:

`include nav`

**Comment by EricWarnke** [comment] 2017-11-11 00:10
Yep, a single include. I swapped it to the plain include without braces and not much difference. I thought if I changed all the includes and their related files to Pug it might help. Now I've got a 5 minute build time, lol...

Only other gem we use is jekyll-redirect-from.

Site is https://mover.io. It's not huge, maybe 30 pages. I could give you private repo access if you're interested.

**Comment by DougBeney** [comment] 2017-11-11 02:38
Nice site and awesome domain!

I think private repo access would be my best bet here. I will have to install Jekyll-Pug from the source (rather than the rubygem package) and will be able to debug easier that way.

**Comment by EricWarnke** [comment] 2017-11-11 19:48
Thanks :)

**Comment by DougBeney** [comment] 2017-11-12 17:45
Ok, so here is what I've found so far. Here is a time breakdown of every Pug file that gets compiled.

One thing you'll notice is that your `nav` include gets rendered a bunch of times. (Every time you try to include it in another file)

So, what I'm thinking is that this plugin **NEEDS** a caching system. Since all of the "dynamic" data is stored in Liquid syntax after Pug compiles, there is zero reason not to implement caching. 

With the caching system, you will theoretically be able to chop 60 seconds off of your compile time.

Going to try to release a new version today. Will let you know of the progress.

Thank you for letting me test with a fairly large project! I work on mostly smaller sites, so this is a discovery I wouldn't have found easily.

| File                              | Time         | 
|-----------------------------------|--------------| 
|  _includes/nav.pug                | 0.456184485  | 
|  _includes/nav.pug                | 0.286067216  | 
|  _includes/nav.pug                | 0.285178544  | 
|  _includes/nav.pug                | 0.285651204  | 
....tons of more files
| TOTAL                             | 62.927050513 |

**Comment by DougBeney** [comment] 2017-11-12 19:27
Man....Tell me this aint beautiful! ![From 60 seconds to 6 second build time](https://i.imgur.com/crdBUcd.png)

Doing some final bug testing and will push this change live.

**Comment by EricWarnke** [comment] 2017-11-12 19:32
That's wicked. Smart idea.

I converted the entire site (not pushed to GitHub) and it shot to over 300 seconds to build, lol. Caching will be excellent.

Looking forward to your changes.

**Comment by DougBeney** [comment] 2017-11-12 20:53
Boom. Version 1.5 of Jekyll-Pug is out. 

Run `bundle update` in your directory and you should be good to go. Do let me know if you run into any other issues.

**Comment by DougBeney** [comment] 2017-11-12 20:54
Oh, also I noticed in your `_config.yml` that you loaded jekyll-pug. I recommend you remove that line from your config. Since it is in your Gemfile, there is no reason to include it in your _config.

**Comment by EricWarnke** [comment] 2017-11-12 20:57
308 seconds down to 4.5... nicely done! Thanks for your help :)

**Comment by DougBeney** [comment] 2017-11-12 21:03
No worries. When you compile for a second time, it should be even faster. 

I recommend adding the following to your gitignore as well if possible: 

```
 Gemfile.lock
.pug-cache
```

**Comment by EricWarnke** [comment] 2017-11-12 21:35
I assume it updates the cache if the files change?

We use Siteleaf.com for some CMS and deployment stuff and they like the gems declared in config.yml.

**Comment by DougBeney** [comment] 2017-11-13 00:06
Just published an update that fixed some Pug include problems I encountered when not using a source folder, Version 1.5.1. When you get a chance, make sure to run `bundle update` again.

Correct. Whenever a file is changed, that single file is recompiled and cached.

**Comment by DougBeney** [comment] 2017-11-13 02:55
Have you tested deploying to SiteLeaf? I'm curious if they will allow the Pug NPM module. Netlify allows you to create a package.json with pug-cli listed as a dependency. Pug-CLI would then be installed automatically while Netlify builds your project.

**Comment by EricWarnke** [comment] 2017-11-13 22:29
SiteLeaf doesn't seem to include your dependencies by default. Can Jekyll-Pug be tweaked to install it's dependencies first?

**Comment by DougBeney** [comment] 2017-11-13 22:46
Going to close this issue since the main problem is solved. I still get notifications for follow-up replies, so you can continue to discuss this here. 

The problem is that you need the NPM package `pug-cli` to be installed. It's up to SiteLeaf to add support for a package.json file, which would have the NPM dependency, pug-cli.

Netlify allows you to have a package.json with the pug-cli package and it will be installed every time you deploy. [See deploying with Netlify](https://github.com/DougBeney/jekyll-pug#deploying-to-netlify).

**Closed as completed by DougBeney** 2017-11-13 22:46 UTC

**Comment by EricWarnke** [comment] 2017-11-13 23:20
I get what Netlify does but SIteleaf is also a wysiwyg for my non-devs.

Any way to get the plugin to install pug-cli using a Ruby script or Gemfile? Siteleaf doesn't support package.json stuff :(

**Comment by DougBeney** [comment] 2017-11-13 23:37
You can't install an NPM module from Ruby, so no unfortunately. Setting up a testing Siteleaf site to see if there are any sort of workarounds or compromises.

**Comment by EricWarnke** [comment] 2017-11-14 17:48
They have great support and an active Slack channel. Here's where I brought up the bug with them initially: https://siteleaf.slack.com/messages/C2NHDN72S/convo/C2NHDN72S-1510606387.000084/

**Comment by DougBeney** [comment] 2018-05-08 16:41
Hi, @EricWarnke! Hope all is going good at Mover!

Just wanted to update you with something cool I've been working on: Jekyll-Bliss.

Its goal is to solve Jekyll's biggest problem (Slow compile times). This will add multi-threading when processing Pug, Sass, and more. It uses Gulp behind the scenes to do so. (The user does not need any sort of gulp config).

It will take away all of the heavy lifting from Jekyll. 

It's nearly a drop-in replacement for Jekyll-Pug.

Let me know what you think. :)

https://github.com/DougBeney/Jekyll-Bliss

**Comment by EricWarnke** [comment] 2018-05-10 04:04
Looks cool. I'll keep an eye on it.

FYI we left Siteleaf and just host on Google Cloud these days.

**Comment by DougBeney** [comment] 2018-05-10 13:31
Still a static site on Google Cloud? Also, you still use some kind of CMS?
